### ISSUE TITLE
When trying import xpub w/ Ledger on wrong network app, the message is not clear.

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#787] opened 2023-11-03 02:50 UTC
![image](https://github.com/wizardsardine/liana/assets/124568858/fccafff3-7083-47e6-8a08-49527fa5e2ad)
Can we detect the Ledger app is loaded on the wrong network?

**Comment by darosior** [comment] 2023-11-03 12:26
Duplicate of https://github.com/wizardsardine/liana/issues/322.

**Closed by darosior** 2023-11-03 12:26 UTC
