### ISSUE TITLE
GUI: do not assume transaction inputs never disappear

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#820] opened 2023-11-17 10:10 UTC
I got a crash at startup when computing the fees here for a Spend whose input disappeared:
https://github.com/wizardsardine/liana/blob/514535d8d6fec705c7271241f68276c42b918150/gui/src/daemon/model.rs#L59-L138

More generally it seems the GUI assumes the inputs for a transaction are always available. It's unfortunately not the case. Unconfirmed transactions often get replaced. They can sometimes disappear. It can also, more rarely, happen to confirmed transactions during a reorg. It's just not something we can assume always holds.

We should not crash (or worse, compute incorrect values) when inputs aren't available. Instead, we could display a placeholder with for instance a tooltip "inputs unavailable for this transaction".

**Comment by darosior** [comment] 2023-11-20 11:51
In fact the GUI can always get the previous output's value from the PSBT input? We always set it when we create a PSBT, and if the user imports a PSBT without it we can just display a placeholder.

**Comment by edouardparis** [comment] 2023-11-20 12:03
Ah good idea, I did not check that. Also what do you think for unconfirmed transaction moved away from the mempool or with coins removed from database to just not display them in the list payments, and list transactions and user can still rebroadcast them through the psbt panel ?

**Comment by darosior** [comment] 2023-11-20 12:08
That makes sense. We could even erase in DB the coins created by an unconfirmed transaction when it gets dropped from the mempool. Any reason why we don't do that currently? There is probably one.

**Comment by darosior** [comment] 2023-11-20 13:01
> So in order to fix our problem we have, if tx is ejected out of mempool:

Is this issue specific to unconfirmed transactions? I thought it would also apply to listing transactions with otherwise unknown inputs.

**Comment by edouardparis** [comment] 2023-11-20 18:00
If coins are missing for confirmed transactions then the gui will only show a wrong history because of missing deposits or missing change but will not crash as we do a check for fee calculation.

**Comment by darosior** [comment] 2023-11-21 16:51
xref https://github.com/wizardsardine/liana/pull/825

**Comment by edouardparis** [comment] 2023-11-29 13:01
closed by #825

**Closed by edouardparis** 2023-11-29 13:01 UTC
Labels: Bug, GUI
