### ISSUE TITLE
bitcoind connection check failed:

### ISSUE THREAD

**Issue by SXBT69** [wizardsardine/liana#1056] opened 2024-03-27 03:39 UTC
<img width="961" alt="Screenshot 2024-03-27 at 4 35 32 AM" src="https://github.com/wizardsardine/liana/assets/137571657/085f1603-2def-4b21-a530-8ceea103925e">

On MacOS M1:
If you delete a wallet and create a new one immediately afterwards, this error is systematic.

the only way to get around it is to delete bitcoind manually...

**Comment by jp1ac4** [comment] 2024-03-27 11:49
Thanks for creating this issue.

I've not been able to reproduce this yet (on Linux). Which version of Liana are you running? Did you delete the wallet using the trash icon when Liana first opens?

**Comment by darosior** [comment] 2024-03-28 11:29
I can't reproduce. I've been through your step, first on regtest and then on signet. I didn't have any issue. I'm testing on a Mac M1 with Liana v5.0rc1.

I have recorded the whole Signet flow so you could tell me if i'm doing something different than you did. Brought to you with a quality recording and my mirrored unshaved face.

First, the Signet install:

https://github.com/wizardsardine/liana/assets/22457751/39ad1d47-d1dc-428e-bea5-476159feb551

Second, once IBD was done, the wallet opens up (i copy the descriptor for later recovery): 

https://github.com/wizardsardine/liana/assets/22457751/07257597-d755-4072-93c6-452b3736fd52

Finally, i delete the Signet wallet and recover it:

https://github.com/wizardsardine/liana/assets/22457751/60c61def-bdbc-4259-9e7f-d522adf133e7

Did i do anything different from you?

**Comment by pythcoiner** [comment] 2024-03-28 19:57
maybe we should notice @darosior is running `Ventura 13.5` vs @SXBT69 running `Sonoma 14.x`

It looks we sharing the same context w/ #928 (also `Sonoma 14.x`)

**Comment by darosior** [comment] 2024-04-01 09:16
Good point, i'll ask the person whom i'm squatting the Mac of to upgrade their system.

**Comment by pythcoiner** [comment] 2024-06-11 09:53
I try to reproduce on a macOS Sonoma VM from master + bitcoind 26.1, but cannot reproduce.
It looks to me it was a bitcoin core auth  w/ cookie [issue](https://github.com/bitcoin/bitcoin/pull/28784) that have been fixed in 26.1.
So i close it, anyone feel free to reopen if upgrading to bitcoind 26.1 don't fix on your side.

**Closed by pythcoiner** 2024-06-11 09:53 UTC
Labels: Bug, MacOS, Can't reproduce
