### ISSUE TITLE
On Mac running macOS Sonoma 14.2.1 and Liana 4.0 and Bitcoin core won't sync past 99.7%

### ISSUE THREAD

**Issue by vazertuche** [wizardsardine/liana#895] opened 2023-12-22 17:34 UTC
Downloaded v4.0 and started a brand new wallet. Deleted both the bitcoin and bitcoind folders. Set up the Bitcoin wallet to restore from a saved descriptor and set Liana to manage the bitcoin node. After a day and a half it downloaded up to 99.7% and now will not go any further. I quit and re-opened several times, no change. I have rebooted several times and opened and still no change. I deleted the wallet and tried restoring again and now it seems frozen at 99.6%....but it will never move further. If I delete the wallet and then create a  brand new wallet using the wallet generated key, still I get stuck at 99.6%. If I delete the bitcoin and bitcoind folders and transfer a previously created bitcoind folder that I backed up to an external drive, I find it works fine. Progress started at 96.5% and ticked up in a few min to 100% and I was good. If i delete the folders again and transfer the previous bitcoind folder I was having problems with back, the same issue persist - stuck at 99.6%. This is NOT the first time this has happened. It is the second. This same issue happened a few months back on version 3 and I ended up just deleting the bitcoind folder and starting fresh.

**Comment by vazertuche** [comment] 2023-12-22 17:35
![Screenshot 2023-12-22 090907](https://github.com/wizardsardine/liana/assets/127354611/b49699d0-c392-4193-af96-1194f313bf87)

**Comment by darosior** [comment] 2023-12-22 21:06
Weird. It's not an issue with the progress rounding: it gets stuck at block `821238`. Can you share the `bitcoind` and `liana-gui` (`/path/to/datadir/bitcoin/liana-gui.log`) logs? (Feel free to email them to me directly if you prefer not sharing them in public.)

Thanks for the report. I'll try to get my hands on a Mac and reproduce.

**Comment by darosior** [comment] 2023-12-22 21:10
One thing which could be interesting to try is to see if `bitcoind` is still responsive. To check you could make an RPC call to `bitcoind` using `bitcoin-cli` (for instance `getblockchaininfo`). To talk to this bitcoind set the `-datadir` option to `/path/to/liana/datadir/bitcoind/datadir`.

**Comment by vazertuche** [comment] 2023-12-22 21:24
Here is the liana-gui.log file via /path/to/datadir/bitcoin/liana-gui.log 
I had already backed up the bitcoind folder and deleted it and started downloading it from scratch. So when I got your email I backed it up, deleted it, and transfered the bad bitcoind folder back and got it started. Left it stuck at 99.6% for a few min and before copying the log file over. 

But you did get me to notice something I didn't before. I have two different bitcoind folders backed up on an external drive made at two different times in the past that both work just fine. When I look at both of them I can see one of the good bitcoind folders has the following folders: bitcoin-25.0, bitcoin-25.1 and datadir. The other one has bitcoin-25.1 and datadir. The one I am having all these issues with has bitcoin-25.1, bitcoin-26.0 and datadir. So MAYBE its the combination of the new version of core with the old version? 
[liana-gui.log](https://github.com/wizardsardine/liana/files/13756783/liana-gui.log)

**Comment by vazertuche** [comment] 2023-12-22 21:27
Not sure how to do what your second comment was asking given that liana is running bitcoind: "One thing which could be interesting to try is to see if bitcoind is still responsive." Need more detailed instructions.

Also for the bitcoind log, is that the debug.log in /bitcoind/datadir/ folder?

**Comment by darosior** [comment] 2023-12-22 21:39
> Also for the bitcoind log, is that the debug.log in /bitcoind/datadir/ folder?

Yes.

**Comment by darosior** [comment] 2023-12-22 21:42
>  [2m2023-12-22T21:13:02.290737Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:13:32.537841Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:14:02.778995Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:14:33.022278Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:15:03.275718Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:15:33.502893Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:16:03.713953Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)    
 [2m2023-12-22T21:16:33.919472Z [0m  [32m INFO [0m  [2mliana::bitcoin::poller::looper [0m [2m: [0m Block chain synchronization progress: 99.60% (821238 blocks / 821238 headers)

So from the Liana logs it appears `bitcoind` is still responsive. It seems to be unaware a longer chain of headers exist.. Very surprising.

**Comment by darosior** [comment] 2024-05-06 10:36
I've just synced a Liana v5 on a Mac M2 with the defaults. Took a while but it did finish successfully with no issue. I'm going to close this as not reproducible. Feel free to leave a comment if you think it should be re-opened.

**Closed by darosior** 2024-05-06 10:36 UTC
