### ISSUE TITLE
Wording on first startup screen

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#544] opened 2023-05-29 11:08 UTC
When starting liana for the first time:
![image](https://github.com/wizardsardine/liana/assets/124568858/a9e62034-be46-483e-b8b5-2eed79291d5c)

"Install liana on another network" should be replace by "Install liana on a new network" if no network installed.

**Comment by darosior** [comment] 2023-05-30 12:36
This is a duplicate of https://github.com/wizardsardine/liana/issues/263.

**Closed by darosior** 2023-05-30 12:36 UTC
