### ISSUE TITLE
Participate mode GUI glitch

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#793] opened 2023-11-03 04:14 UTC
When creating a wallet in ‘participate mode’ if we click several times on the ‘this computer....’, every click we add one more ~~descriptor~~ xpub (always the same)
![image](https://github.com/wizardsardine/liana/assets/124568858/420bdd75-edfe-4cfc-8818-4b59094563b1)

**Comment by darosior** [comment] 2023-11-03 12:17
I thought we had fixed that... Thanks.

> every click we add one more descriptor

I think you meant "xpub" here.

**Comment by pythcoiner** [comment] 2023-11-04 21:18
Yes xpub, i should drink my coffee BEFORE openning issues in batch 😂

**Comment by edouardparis** [comment] 2023-12-08 11:27
Cannot reproduce the issue on master.
It seems it was fixed on v3 https://github.com/wizardsardine/liana/commit/4be74ad496692d371adffcc1b3c868ef6a01cb52#diff-60bfa44049766e833c1f2d902b127539e4f93a5773d2ebb0516e2d9291326383R1064

**Comment by darosior** [comment] 2023-12-08 12:08
Indeed. Great news!

**Closed by darosior** 2023-12-08 12:08 UTC
Labels: GUI, Glitch
