### ISSUE TITLE
GUI: please make it clear that people need to click on their wallet to register the descriptor

### ISSUE THREAD

**Issue by mariabmont** [wizardsardine/liana#247] opened 2022-12-16 16:02 UTC
![image](https://user-images.githubusercontent.com/118536288/208138862-6b989c11-fcf7-43a3-b5a3-218a35ebeaae.png)

in this image i just clicked "next" instead of registering the descriptor in one of the wallets.

**Comment by darosior** [comment] 2022-12-18 08:57
Yes. I've been arguing we shouldn't allow users to continue without registering the descriptor on their device. But a good point from Edouard is that for Ledger the device doesn't know that itself.

For sure as a first step it should clearer users need to click on those tiles.

**Comment by darosior** [comment] 2022-12-18 09:00
Actually @edouardparis can't we just check if we have the hmac for the Ledger? If we don't, we prevent the user from continuing without registering the descriptor. If we need to check if we have the hmac for the right descriptor we could ask the device to generate an address at a specific derivation index.

**Comment by darosior** [comment] 2022-12-18 10:26
This is a duplicate of #187 actually. But i'll keep this one open since it contains more details and discussion.

**Comment by darosior** [comment] 2023-02-05 14:38
I think this was fixed in https://github.com/wizardsardine/liana/pull/315. :tada:

**Closed by darosior** 2023-02-05 14:38 UTC
Labels: GUI, Feature
