### ISSUE TITLE
We need airgap foss function in liana!!

### ISSUE THREAD

**Issue by Garrysoon** [wizardsardine/liana#1091] opened 2024-05-12 06:25 UTC
Airgap for DIY hardware wallets, like Krux, SeedSigner!

**Comment by Garrysoon** [comment] 2024-05-12 06:35
it would be fantastic

**Comment by pythcoiner** [comment] 2024-05-12 13:35
Hi, we start talking about this in #539

**Comment by darosior** [comment] 2024-05-15 08:46
Closing as duplicate of #539.

**Closed by darosior** 2024-05-15 08:46 UTC
