### ISSUE TITLE
Minimum size for Liana Installer window

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#590] opened 2023-08-05 07:13 UTC
Widgets get cut/compressed/disapear if the user resize the window too small:
![ezgif-4-36a4873465](https://github.com/wizardsardine/liana/assets/124568858/72afb4b9-5f94-4881-b8fa-2e141b5c89fa)

**Comment by darosior** [comment] 2023-08-07 06:38
Duplicate of https://github.com/wizardsardine/liana/issues/506.

**Closed by darosior** 2023-08-07 06:38 UTC
