### ISSUE TITLE
extended key with origin rejected for not having origin

### ISSUE THREAD

**Issue by turkycat** [wizardsardine/liana#564] opened 2023-06-30 22:31 UTC
I've just started playing with Liana, but I thought I'd start with importing some very basic wallets before exploring the timelock options.

The simplest repro of an issue I saw is to try to import this descriptor with one key: `wpkh([7737acb8]tpubD6NzVbkrYhZ4X3vCdevm3aFUdeSAWsbR4UhhdApbXnVUnvuwtq5NYqQ7zCkNhYG4JcPdGW4Wg4ZrVSYGpdoWsn337qmkP6CFgs7pZid12Sa/0/*)`

Error is: 
"Incompatible descriptor. Note that starting from v0.2 Liana requires extended keys in a descriptor to have an origin"

from the patch notes on V.2:
> Liana forces extended keys to contain an origin (of the form [a1b2c3d4]) to avoid this footgun.

I believe "[7737acb8]" is my key's 'origin'. Maybe I'm misunderstanding something, because this is typically called a fingerprint. Are these indeed two different things? The examples from the root documentation don't appear to include other metadata per key.

**Comment by pythcoiner** [comment] 2023-07-01 06:49
you should add a derivation path : 

wpkh([7737acb8`/48'/1'/1'/2'`]tpubD6NzVbkrYhZ4X3vCdevm3aFUdeSAWsbR4UhhdApbXnVUnvuwtq5NYqQ7zCkNhYG4JcPdGW4Wg4ZrVSYGpdoWsn337qmkP6CFgs7pZid12Sa/`<0;1>`/*)

**Comment by darosior** [comment] 2023-07-01 09:00
No, it's not an issue of requiring a derivation path. The issue is that Liana requires a specific type of descriptor, to make sure some invariants hold. Only accepted descriptors are ones containing at least one, immediately available, spending path along with one or more timelocked spending paths.

It's not the case with your descriptor, that is why it gets refused. The last sentence in the error message is a hint for a common reason why descriptors are refused. But by no mean it's the only possible cause. Maybe we should make this clearer?

> I believe "[7737acb8]" is my key's 'origin'. Maybe I'm misunderstanding something, because this is typically called a fingerprint.

The origin in a descriptor key expression is the combination of both a fingerprint and a derivation path that describe what xpub this key was derived from.

**Comment by darosior** [comment] 2023-07-01 09:01
I'm going to close this, feel free to reopen if you think that's still an issue. (It's also perfectly fine if you want to open a PR or an issue suggesting a better wording for the error message!)

**Closed by darosior** 2023-07-01 09:01 UTC
